package rx

import "time"

// Ref ссылка на сущность: Id и имя.
type Ref struct {
	ID   int64  `json:"Id"`
	Name string `json:"Name"`
}

// User пользователь RX.
type User struct {
	ID     int64  `json:"Id"`
	Name   string `json:"Name"`
	Status string `json:"Status"`
	Login  *struct {
		LoginName          string `json:"LoginName"`
		TypeAuthentication string `json:"TypeAuthentication"`
	} `json:"Login"`
}

// Employee сотрудник.
type Employee struct {
	ID         int64  `json:"Id"`
	Name       string `json:"Name"`
	Status     string `json:"Status"`
	Email      string `json:"Email"`
	Phone      string `json:"Phone"`
	Department *Ref   `json:"Department"`
	JobTitle   *Ref   `json:"JobTitle"`
}

// Text запись переписки по задаче или заданию.
type Text struct {
	Created         *time.Time `json:"Created"`
	Body            string     `json:"Body"`
	IsAutoGenerated bool       `json:"IsAutoGenerated"`
	Author          *Ref       `json:"Author"`
}

// Attachment вложение.
type Attachment struct {
	AttachmentID int64      `json:"AttachmentId"`
	AttachedAt   *time.Time `json:"AttachedAt"`
}

// TaskRef краткая задача.
type TaskRef struct {
	ID      int64  `json:"Id"`
	Subject string `json:"Subject"`
	Status  string `json:"Status"`
}

// Assignment задание или уведомление.
type Assignment struct {
	Type        string       `json:"@odata.type"`
	ID          int64        `json:"Id"`
	Subject     string       `json:"Subject"`
	Status      string       `json:"Status"`
	Importance  string       `json:"Importance"`
	Deadline    *time.Time   `json:"Deadline"`
	Created     *time.Time   `json:"Created"`
	Modified    *time.Time   `json:"Modified"`
	Completed   *time.Time   `json:"Completed"`
	IsRead      bool         `json:"IsRead"`
	Result      string       `json:"Result"`
	Performer   *Ref         `json:"Performer"`
	Author      *Ref         `json:"Author"`
	Task        *TaskRef     `json:"Task"`
	Texts       []Text       `json:"Texts"`
	Attachments []Attachment `json:"AttachmentDetails"`
}

// Task задача.
type Task struct {
	ID          int64        `json:"Id"`
	Subject     string       `json:"Subject"`
	Status      string       `json:"Status"`
	Importance  string       `json:"Importance"`
	Created     *time.Time   `json:"Created"`
	Started     *time.Time   `json:"Started"`
	MaxDeadline *time.Time   `json:"MaxDeadline"`
	Author      *Ref         `json:"Author"`
	StartedBy   *Ref         `json:"StartedBy"`
	Texts       []Text       `json:"Texts"`
	Attachments []Attachment `json:"AttachmentDetails"`
}

// Version версия документа.
type Version struct {
	ID       int64      `json:"Id"`
	Number   int        `json:"Number"`
	Note     string     `json:"Note"`
	Created  *time.Time `json:"Created"`
	IsHidden bool       `json:"IsHidden"`
	App      *struct {
		Name      string `json:"Name"`
		Extension string `json:"Extension"`
	} `json:"AssociatedApplication"`
}

// Document электронный документ, с полями официального, если есть.
type Document struct {
	ID                 int64      `json:"Id"`
	Name               string     `json:"Name"`
	Created            *time.Time `json:"Created"`
	Modified           *time.Time `json:"Modified"`
	HasVersions        bool       `json:"HasVersions"`
	Author             *Ref       `json:"Author"`
	DocumentKind       *Ref       `json:"DocumentKind"`
	Versions           []Version  `json:"Versions"`
	Subject            string     `json:"Subject"`
	Note               string     `json:"Note"`
	RegistrationNumber string     `json:"RegistrationNumber"`
	RegistrationDate   *time.Time `json:"RegistrationDate"`
	DocumentDate       *time.Time `json:"DocumentDate"`
	LifeCycleState     string     `json:"LifeCycleState"`
	RegistrationState  string     `json:"RegistrationState"`
	InternalApproval   string     `json:"InternalApprovalState"`
	ExternalApproval   string     `json:"ExternalApprovalState"`
	ExecutionState     string     `json:"ExecutionState"`
	Department         *Ref       `json:"Department"`
	BusinessUnit       *Ref       `json:"BusinessUnit"`
	OurSignatory       *Ref       `json:"OurSignatory"`
	Assignee           *Ref       `json:"Assignee"`
}
